### ISSUE TITLE
@conda-forge-admin, please add user @swryan

### ISSUE THREAD

**Issue by swryan** [conda-forge/openmdao-feedstock#46]
### Additional comment:

@bollwyvl I've decided to take you up on getting added as a maintainer per the discussion in PR #43.

Things have been working smoothly with this recipe (Thank You!), but after experiencing hiccups with a sister [project](https://github.com/conda-forge/dymos-feedstock), it's clear that having a member of the dev team on board is a good idea.

Thanks again for your support with this!

**Comment by bollwyvl** [comment]
JOIN US :vulcan_salute:
